idea.config.path=${user.home}/.config/webstorm/config
idea.system.path=${user.home}/.cache/webstorm/system
idea.plugins.path=${user.home}/.local/share/webstorm/plugins
idea.log.path=${user.home}/.local/state/webstorm/log
